INSERT INTO public.part(brand, cost, description, is_available, model, name, production_time_in_hours_min, production_time_in_hours_max, shipping_time) VALUES ('Audi', 300.50, 'black small handle', true, 'A4', 'handle', 1, 3, 21);
INSERT INTO public.part(brand, cost, description, is_available, model, name, production_time_in_hours_min, production_time_in_hours_max, shipping_time) VALUES ('Audi', 2500, 'front left mirror', true, 'A4', 'mirror', 5, 12, 3);
INSERT INTO public.part(brand, cost, description, is_available, model, name, production_time_in_hours_min, production_time_in_hours_max, shipping_time) VALUES ('Audi', 4000.99, 'front', false, 'Q7', 'window', 4, 12, 1);
INSERT INTO public.part(brand, cost, description, is_available, model, name, production_time_in_hours_min, production_time_in_hours_max, shipping_time) VALUES ('BMW', 5000.45, 'left led', true, 'X3', 'headlight', 7, 15, 2);
INSERT INTO public.part(brand, cost, description, is_available, model, name, production_time_in_hours_min, production_time_in_hours_max, shipping_time) VALUES ('BMW', 300.50, 'right front', false, 'X5', 'door', 15, 22, 4);
INSERT INTO public.part(brand, cost, description, is_available, model, name, production_time_in_hours_min, production_time_in_hours_max, shipping_time) VALUES ('BMW', 300.50, 'front left leather', true, 'E36', 'seat', 12, 15, 6);
INSERT INTO public.part(brand, cost, description, is_available, model, name, production_time_in_hours_min, production_time_in_hours_max, shipping_time) VALUES ('Porsche', 250.50, '45/55/17R', true, 'Panamera', 'tire', 12, 45, 2);
INSERT INTO public.part(brand, cost, description, is_available, model, name, production_time_in_hours_min, production_time_in_hours_max, shipping_time) VALUES ('Porsche', 3000.22, 'black', false, 'Cayenne', 'bumpers', 11, 13, 3);
INSERT INTO public.part(brand, cost, description, is_available, model, name, production_time_in_hours_min, production_time_in_hours_max, shipping_time) VALUES ('Porsche', 422, 'front small left', true, '911', 'turn signal', 2, 5, 2);
INSERT INTO public.part(brand, cost, description, is_available, model, name, production_time_in_hours_min, production_time_in_hours_max, shipping_time) VALUES ('Alfa Romeo', 536.50, 'new', false, 'Guiletta', 'radiator', 1, 6, 1);
INSERT INTO public.part(brand, cost, description, is_available, model, name, production_time_in_hours_min, production_time_in_hours_max, shipping_time) VALUES ('Mercedes-benz', 764, 'new', true, 'A180', 'alternator', 3, 7, 4);
INSERT INTO public.part(brand, cost, description, is_available, model, name, production_time_in_hours_min, production_time_in_hours_max, shipping_time) VALUES ('Mercedes-benz', 352, 'used', true, 'C63 AMG', 'oil filter', 2, 9, 6);
INSERT INTO public.part(brand, cost, description, is_available, model, name, production_time_in_hours_min, production_time_in_hours_max, shipping_time) VALUES ('Mercedes-benz', 746.88, 'used', true, 'CLA', 'fuel filter', 6, 12, 7);
INSERT INTO public.part(brand, cost, description, is_available, model, name, production_time_in_hours_min, production_time_in_hours_max, shipping_time) VALUES ('Fiat', 547.54, null, true, '126p', 'air filter', 7, 13, 2);
INSERT INTO public.part(brand, cost, description, is_available, model, name, production_time_in_hours_min, production_time_in_hours_max, shipping_time) VALUES ('Fiat', 223.33, 'round grey', false, 'Panda', 'steering wheel', 4, 6, 3);
INSERT INTO public.part(brand, cost, description, is_available, model, name, production_time_in_hours_min, production_time_in_hours_max, shipping_time) VALUES ('Volvo', 578.76, '12V', true, 'V40', 'battery', 4, 8, 2);
INSERT INTO public.part(brand, cost, description, is_available, model, name, production_time_in_hours_min, production_time_in_hours_max, shipping_time) VALUES ('Volvo', 127.54, null, false, 'S60', 'disk brake', 5, 8, 4);
INSERT INTO public.part(brand, cost, description, is_available, model, name, production_time_in_hours_min, production_time_in_hours_max, shipping_time) VALUES ('Peugeot', 680.55, null, false, '206', 'radiator', 4, 8, 1);
INSERT INTO public.part(brand, cost, description, is_available, model, name, production_time_in_hours_min, production_time_in_hours_max, shipping_time) VALUES ('Peugeot', 453.58, '55/45/17R', true, '307', 'tire', 1, 6, 2);
INSERT INTO public.part(brand, cost, description, is_available, model, name, production_time_in_hours_min, production_time_in_hours_max, shipping_time) VALUES ('Peugeot', 100.25, 'XSDGSD2223', false, '3008', 'oil filter', 2, 8, 1);

INSERT INTO public.sales_argument(argument, part_id) VALUES ('argument1', 1);
INSERT INTO public.sales_argument(argument, part_id) VALUES ('argument2', 1);
INSERT INTO public.sales_argument(argument, part_id) VALUES ('argument3', 2);
INSERT INTO public.sales_argument(argument, part_id) VALUES ('argument4', 3);
INSERT INTO public.sales_argument(argument, part_id) VALUES ('argument5', 3);
INSERT INTO public.sales_argument(argument, part_id) VALUES ('argument6', 5);
INSERT INTO public.sales_argument(argument, part_id) VALUES ('argument7', 5);
INSERT INTO public.sales_argument(argument, part_id) VALUES ('argument8', 12);
INSERT INTO public.sales_argument(argument, part_id) VALUES ('argument9', 17);
INSERT INTO public.sales_argument(argument, part_id) VALUES ('argument10', 17);
INSERT INTO public.sales_argument(argument, part_id) VALUES ('argument11', 19);
INSERT INTO public.sales_argument(argument, part_id) VALUES ('argument12', 19);
INSERT INTO public.sales_argument(argument, part_id) VALUES ('argument13', 19);
INSERT INTO public.sales_argument(argument, part_id) VALUES ('argument14', 20);
INSERT INTO public.sales_argument(argument, part_id) VALUES ('argument15', 20);

INSERT INTO public.service_action(action_finish_date, action_start_date, name, part_id) VALUES ('2020-09-15', '2020-09-13', 'exchange', 1);
INSERT INTO public.service_action(action_finish_date, action_start_date, name, part_id) VALUES ('2020-09-12', '2020-09-11', 'sell', 1);
INSERT INTO public.service_action(action_finish_date, action_start_date, name, part_id) VALUES ('2020-09-06', '2020-09-02', 'fix', 3);
INSERT INTO public.service_action(action_finish_date, action_start_date, name, part_id) VALUES ('2020-09-04', '2020-09-03', 'return', 4);
INSERT INTO public.service_action(action_finish_date, action_start_date, name, part_id) VALUES ('2020-08-27', '2020-08-25', 'exchange', 5);
INSERT INTO public.service_action(action_finish_date, action_start_date, name, part_id) VALUES ('2020-09-05', '2020-09-02', 'sell', 5);
INSERT INTO public.service_action(action_finish_date, action_start_date, name, part_id) VALUES ('2020-08-15', '2020-08-11', 'return', 8);
INSERT INTO public.service_action(action_finish_date, action_start_date, name, part_id) VALUES ('2020-09-09', '2020-09-05', 'fix', 8);
INSERT INTO public.service_action(action_finish_date, action_start_date, name, part_id) VALUES ('2020-07-15', '2020-07-11', 'return', 12);
INSERT INTO public.service_action(action_finish_date, action_start_date, name, part_id) VALUES ('2020-07-15', '2020-07-12', 'sell', 12);
INSERT INTO public.service_action(action_finish_date, action_start_date, name, part_id) VALUES ('2020-07-12', '2020-07-09', 'fix', 16);
INSERT INTO public.service_action(action_finish_date, action_start_date, name, part_id) VALUES ('2020-08-18', '2020-08-11', 'sell', 16);
INSERT INTO public.service_action(action_finish_date, action_start_date, name, part_id) VALUES ('2020-08-17', '2020-08-10', 'exchange', 16);
INSERT INTO public.service_action(action_finish_date, action_start_date, name, part_id) VALUES ('2020-05-22', '2020-05-15', 'fix', 18);
INSERT INTO public.service_action(action_finish_date, action_start_date, name, part_id) VALUES ('2020-05-27', '2020-05-15', 'exchange', 18);